steps:
  # Install backend dependencies
  - id: install
    name: gcr.io/cloud-builders/npm
    dir: backend
    args: ['ci']

  # Run the backend unit tests
  - id: test
    name: gcr.io/cloud-builders/npm
    dir: backend
    args: ['test', '--', '--runInBand']

  # Build the multi-stage container image
  - id: build-image
    name: gcr.io/cloud-builders/docker
    args: ['build','-f','backend/Dockerfile','-t','gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA','backend']

  # Push the image to Container Registry
  - id: push-image
    name: gcr.io/cloud-builders/docker
    args: ['push','gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']

  # Deploy the image to Cloud Run
  - id: deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - >-
        GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID,
        GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET,
        GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI,
        FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT

images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: learning-hub

timeout: '1200s'
