steps:
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    dir: 'backend'
    args: ['test']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/learning-hub', 'backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'learning-hub', '--image', 'gcr.io/$PROJECT_ID/learning-hub', '--region', 'us-central1', '--platform', 'managed', '--quiet']
images:
  - 'gcr.io/$PROJECT_ID/learning-hub'
