steps:
  - name: gcr.io/cloud-builders/npm
    dir: backend
    args: ['install']
  - name: gcr.io/cloud-builders/npm
    dir: backend
    args: ['test']
  - name: gcr.io/cloud-builders/docker
    args: ['build','-t','gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA','backend']
  - name: gcr.io/cloud-builders/docker
    args: ['push','gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - --image
      - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET,GOOGLE_REDIRECT_URI=$GOOGLE_REDIRECT_URI,FIREBASE_SERVICE_ACCOUNT=$FIREBASE_SERVICE_ACCOUNT
images:
  - gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA
substitutions:
  _REGION: us-central1
  _SERVICE_NAME: learning-hub
